#ifndef __PROJECT_CONF_H__
#define __PROJECT_CONF_H__


//#undef NETSTACK_CONF_MAC
//#define NETSTACK_CONF_MAC     nullmac_driver /*csma_driver*/

#undef NETSTACK_CONF_RDC
#define NETSTACK_CONF_RDC     nullrdc_driver 

#undef NETSTACK_CONF_FRAMER
#define NETSTACK_CONF_FRAMER framer_802154   
  
//#undef	CC2420_CONF_AUTOACK 
//#define CC2420_CONF_AUTOACK 	0

/*
#undef NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE
#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 8

#undef CXMAC_CONF_ANNOUNCEMENTS
#define CXMAC_CONF_ANNOUNCEMENTS       1

*/

#define DATA_INTERVAL	CMD_DATA_INTERVAL


#endif /*__PROJECT_CONF_H__*/
